name: Publish new posts as newsletter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Publish newsletter
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Detect changed files in commit
        id: added-posts
        uses: tj-actions/changed-files@v17.3
        with:
          path: content/posts

      - name: List all added posts
        run: |
          for file in ${{ steps.added-posts.outputs.added_files }}; do
            echo "$file was added"
          done
