# This is a basic workflow to help you get started with Actions

name: Send post to Buttondown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run changed-files with defaults on the dir1
        id: changed-files-for-posts
        uses: tj-actions/changed-files@v17.3
        with:
          path: content/posts

      - name: List all added files in posts
        run: |
          for file in ${{ steps.changed-files-for-posts.outputs.added_files }}; do
            echo "$file was added"
          done
